# Generated by Django 4.2.7 on 2024-01-13 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udyamhelper', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='members_after_1st_year',
            new_name='members_after_first_year',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='members_from_1st_year',
            new_name='members_from_first_year',
        ),
        migrations.AlterField(
            model_name='event',
            name='event',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='noticeboard',
            name='event',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='teamname',
            field=models.CharField(max_length=100),
        ),
    ]
