# Generated by Django 5.0 on 2024-03-01 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('udyam', '0005_remove_event_date_remove_event_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='name',
        ),
    ]
